version: "2.0"

services:
    zookeeper:
      image: wurstmeister/zookeeper
      container_name: compose-zookeeper
      restart: always
      ports:
        - "2181:2181"
        
    kafka:
      image: wurstmeister/kafka
      container_name: compose-kafka
      depends_on: [ zookeeper ]
      restart: always
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: lcalhost
        KAFKA_CREATE_TOPICS: "test:1:1"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       volumes:
        - "./compose/kafka/docker.sock:/var/run/docker.sock"

    mysql:
      restart: always
      image: mysql
      container_name: compose-mysql
      ports:
        - "3306:3306"
      volumes: 
          - ./compose/mysql/conf:/etc/mysql/conf.d
          - ./compose/mysql/logs:/logs
          - ./compose/mysql/data:/var/lib/mysql
          
      environment:
        MYSQL_ROOT_PASSWORD: 123456

    redis:
      image: redis
      container_name: compose-redis
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - "./compose/redis:/data"

    aspcorerestapi:
      build: .
      container_name: compose-aspcorerestapi
      depends_on: [kafka,mysql,redis]
      restart: always
      ports:
        - "80:80"
